// docs/docs-and-web-client/src/components/TypingHelper.svelte
<script lang="ts">
  import { type ScriptListType, SCRIPT_LIST } from 'lipilekhika';
  import { getScriptKramaData, getScriptTypingDataMap } from 'lipilekhika/typing';

  import * as Dialog from '$lib/components/ui/dialog';
  import * as Select from '$lib/components/ui/select';
  import * as Tabs from '$lib/components/ui/tabs';
  import { Badge } from '$lib/components/ui/badge';
  import { Skeleton } from '$lib/components/ui/skeleton';

  import { Keyboard, Map as MapIcon, ArrowLeftRight } from 'lucide-svelte';
  import ScriptSeleector from './script/ScriptSelector.svelte';

  let { open = $bindable(), script: script_input } = $props<{
    open: boolean;
    script: ScriptListType;
  }>();

  // svelte-ignore state_referenced_locally
  let script = $state<ScriptListType>(script_input);

  let script_to_compare = $state<ScriptListType | undefined>('Romanized');

  let script_typing_map_promise = $derived(getScriptTypingDataMap(script));

  let base_script_krama_prom = $derived(getScriptKramaData(script));
  let script_to_compare_krama_prom = $derived(
    script_to_compare ? getScriptKramaData(script_to_compare) : null
  );

  type ListType = 'svara' | 'vyanjana' | 'anya' | 'mAtrA';
  type Item = [text: string, type: ListType, mappings: string[]];
  type KramaRow = [text: string, type: ListType];

  const isSvara = (t: ListType) => t === 'svara' || t === 'mAtrA';

  const filterCategory = (items: Item[], category: 'svara' | 'vyanjana' | 'anya') => {
    if (category === 'svara') return items.filter(([, t]) => isSvara(t));
    if (category === 'vyanjana') return items.filter(([, t]) => t === 'vyanjana');
    return items.filter(([, t]) => t === 'anya');
  };
</script>

<Dialog.Root bind:open>
  <Dialog.Content
    class="w-[95vw] max-w-4xl p-0 sm:w-full sm:max-w-3xl"
    aria-describedby="typing-helper-description"
  >
    <div class="flex max-h-[85vh] flex-col">
      <div class="flex items-start justify-between gap-4 p-5 sm:p-6">
        <div class="min-w-0">
          <div class="flex items-center gap-2">
            <Keyboard class="size-5 text-primary" />
            <Dialog.Title class="truncate text-base font-semibold sm:text-lg">
              Typing help
            </Dialog.Title>
          </div>
        </div>
      </div>

      <div class="min-h-0 flex-1 overflow-y-auto p-5 sm:p-6">
        <div class="mb-4 flex items-center justify-center gap-x-2">
          <span class="text-sm text-muted-foreground">Select Script</span>
          <ScriptSeleector bind:script />
        </div>

        <Tabs.Root value="typing-map" class="flex h-full min-h-0 flex-col">
          <Tabs.List class="grid w-full grid-cols-2">
            <Tabs.Trigger value="typing-map" class="gap-2">
              <MapIcon class="size-4" />
              Typing Map
            </Tabs.Trigger>
            <Tabs.Trigger value="compare-scripts" class="gap-2">
              <ArrowLeftRight class="size-4" />
              Compare Scripts
            </Tabs.Trigger>
          </Tabs.List>

          <Tabs.Content value="typing-map" class="mt-4 flex-1 pr-1">
            {#await script_typing_map_promise}
              <section class="space-y-6" aria-label="Loading typing map">
                {#each ['Svara', 'Vyanjana', 'Other', 'Script-specific Characters'] as title (title)}
                  <div>
                    <div class="mb-2 flex items-center justify-between gap-2">
                      <Skeleton class="h-6 w-40" />
                    </div>
                    <div class="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4">
                      {#each Array.from({ length: 12 }) as _, idx (title + idx)}
                        <div class="rounded-md border border-border bg-card p-2">
                          <Skeleton class="h-6 w-14" />
                          <div class="mt-2 flex flex-wrap gap-1">
                            <Skeleton class="h-4 w-10 opacity-70" />
                            <Skeleton class="h-4 w-12 opacity-60" />
                            <Skeleton class="h-4 w-14 opacity-50" />
                          </div>
                        </div>
                      {/each}
                    </div>
                  </div>
                {/each}
              </section>
            {:then script_typing_map}
              {@const common = script_typing_map.common_krama_map as Item[]}
              {@const specific = script_typing_map.script_specific_krama_map as Item[]}
              {@const svaraItems = filterCategory(common, 'svara')}
              {@const vyanjanaItems = filterCategory(common, 'vyanjana')}
              {@const otherItems = filterCategory(common, 'anya')}

              <section class="space-y-6">
                <!-- Svara -->
                <div>
                  <div class="mb-2 flex items-center justify-between gap-2">
                    <h3 class="text-lg font-semibold tracking-wide">Svara</h3>
                  </div>
                  <div class="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4">
                    {#each svaraItems as [char, type, mappings] (char + type)}
                      <div
                        class="rounded-md border border-border bg-card p-2 transition-all focus-within:ring-2 focus-within:ring-ring/50 focus-within:ring-offset-2 focus-within:ring-offset-background hover:-translate-y-0.5 hover:border-foreground/20 hover:bg-accent/30 hover:shadow-md"
                      >
                        <div class="flex items-start justify-between gap-2">
                          <div class="text-xl leading-none font-semibold">{char}</div>
                        </div>
                        <div
                          class="mt-1 flex max-h-20 flex-wrap items-start gap-1 overflow-auto pr-1"
                          aria-label="Typing mappings"
                        >
                          {#each mappings as m (m)}
                            <Badge variant="outline" class="px-1.5 py-0 text-[10px]">
                              <code class="font-mono text-[10px]">{m}</code>
                            </Badge>
                          {/each}
                        </div>
                      </div>
                    {/each}
                  </div>
                </div>

                <!-- Vyanjana -->
                <div>
                  <div class="mb-2 flex items-center justify-between gap-2">
                    <h3 class="text-lg font-semibold tracking-wide">Vyanjana</h3>
                  </div>
                  <div class="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4">
                    {#each vyanjanaItems as [char, type, mappings] (char + type)}
                      <div
                        class="rounded-md border border-border bg-card p-2 transition-all focus-within:ring-2 focus-within:ring-ring/50 focus-within:ring-offset-2 focus-within:ring-offset-background hover:-translate-y-0.5 hover:border-foreground/20 hover:bg-accent/30 hover:shadow-md"
                      >
                        <div class="flex items-start justify-between gap-2">
                          <div class="text-xl leading-none font-semibold">{char}</div>
                        </div>
                        <div class="mt-1 flex max-h-20 flex-wrap gap-1 overflow-auto pr-1">
                          {#each mappings as m (m)}
                            <Badge variant="outline" class="px-1.5 py-0 text-[10px]">
                              <code class="font-mono text-[10px]">{m}</code>
                            </Badge>
                          {/each}
                        </div>
                      </div>
                    {/each}
                  </div>
                </div>

                <!-- Other -->
                <div>
                  <div class="mb-2 flex items-center justify-between gap-2">
                    <h3 class="text-lg font-semibold tracking-wide">Other</h3>
                  </div>
                  <div class="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4">
                    {#each otherItems as [char, type, mappings] (char + type)}
                      <div
                        class="rounded-md border border-border bg-card p-2 transition-all focus-within:ring-2 focus-within:ring-ring/50 focus-within:ring-offset-2 focus-within:ring-offset-background hover:-translate-y-0.5 hover:border-foreground/20 hover:bg-accent/30 hover:shadow-md"
                      >
                        <div class="flex items-start justify-between gap-2">
                          <div class="text-xl leading-none font-semibold">{char}</div>
                        </div>
                        <div class="mt-1 flex max-h-20 flex-wrap gap-1 overflow-auto pr-1">
                          {#each mappings as m (m)}
                            <Badge variant="outline" class="px-1.5 py-0 text-[10px]">
                              <code class="font-mono text-[10px]">{m}</code>
                            </Badge>
                          {/each}
                        </div>
                      </div>
                    {/each}
                  </div>
                </div>

                <!-- Script-specific preview -->
                <div>
                  <div class="mb-2 flex items-center justify-between gap-2">
                    <h3 class="text-lg font-semibold tracking-wide">Script-specific Characters</h3>
                  </div>
                  <div class="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4">
                    {#each specific as [char, type, mappings] (char + type)}
                      <div
                        class="rounded-md border border-border bg-card p-2 transition-all focus-within:ring-2 focus-within:ring-ring/50 focus-within:ring-offset-2 focus-within:ring-offset-background hover:-translate-y-0.5 hover:border-foreground/20 hover:bg-accent/30 hover:shadow-md"
                      >
                        <div class="flex items-start justify-between gap-2">
                          {#if char !== '\u200d'}
                            <div class="text-xl leading-none font-semibold">{char}</div>
                          {:else}
                            <div class="text-xs leading-none font-semibold">zero width joiner</div>
                          {/if}
                        </div>
                        <div class="mt-1 flex max-h-20 flex-wrap gap-1 overflow-auto pr-1">
                          {#if mappings.length === 0}
                            <span class="text-xs text-muted-foreground">No mappings</span>
                          {:else}
                            {#each mappings as m (m)}
                              <Badge variant="outline" class="px-1.5 py-0 text-[10px]">
                                <code class="font-mono text-[10px]">{m}</code>
                              </Badge>
                            {/each}
                          {/if}
                        </div>
                      </div>
                    {/each}
                  </div>
                </div>
              </section>
            {:catch err}
              <div class="rounded-lg border border-destructive/30 bg-destructive/5 p-4 text-sm">
                <p class="font-medium text-destructive">Could not load typing map</p>
                <p class="mt-1 text-xs text-muted-foreground">{String(err)}</p>
              </div>
            {/await}
          </Tabs.Content>

          <Tabs.Content value="compare-scripts" class="mt-4 flex-1 pr-1">
            <div class="space-y-4">
              <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                <div class="text-sm text-muted-foreground">
                  Current script: <span class="font-medium text-foreground">{script}</span>
                </div>

                <div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:gap-3">
                  <span class="text-sm text-muted-foreground">Compare with</span>
                  <Select.Root type="single" bind:value={script_to_compare}>
                    <Select.Trigger
                      class={`w-full sm:w-64 ${!script_to_compare ? 'text-muted-foreground' : ''}`}
                    >
                      {script_to_compare ?? 'Select a script'}
                    </Select.Trigger>
                    <Select.Content>
                      {#each (SCRIPT_LIST as ScriptListType[]).filter((s) => s !== script && s !== 'Normal') as s (s)}
                        <Select.Item value={s} label={s} />
                      {/each}
                    </Select.Content>
                  </Select.Root>
                </div>
              </div>

              {#if !script_to_compare}
                <div
                  class="rounded-lg border border-border bg-card p-4 text-sm text-muted-foreground"
                >
                  Select a script to compare against <span class="font-medium">{script}</span>.
                </div>
              {:else}
                {@const compareProm = script_to_compare_krama_prom as Promise<KramaRow[]>}
                {#await Promise.all([base_script_krama_prom as Promise<KramaRow[]>, compareProm])}
                  <!-- Skeleton: only shown while a compare script is selected and data is loading -->
                  <div class="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4">
                    {#each Array.from({ length: 12 }) as _, idx (idx)}
                      <div class="rounded-md border border-border bg-card p-2">
                        <Skeleton class="h-6 w-14" />
                        <div class="mt-2"></div>
                        <Skeleton class="h-6 w-14 opacity-70" />
                      </div>
                    {/each}
                  </div>
                {:then [base, compare]}
                  <div class="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4">
                    {#each base as [baseText], i (baseText + i)}
                      {#if baseText.length !== 0}
                        <div
                          class="rounded-md border border-border bg-card p-2 transition-all focus-within:ring-2 focus-within:ring-ring/50 focus-within:ring-offset-2 focus-within:ring-offset-background hover:-translate-y-0.5 hover:border-foreground/20 hover:bg-accent/30 hover:shadow-md"
                        >
                          <div class="text-xl leading-none font-semibold">{baseText}</div>
                          <div
                            class="mt-1 text-xl leading-none font-semibold text-muted-foreground"
                          >
                            {compare[i]?.[0] ?? '—'}
                          </div>
                        </div>
                      {/if}
                    {/each}
                  </div>
                {:catch err}
                  <div class="rounded-lg border border-destructive/30 bg-destructive/5 p-4 text-sm">
                    <p class="font-medium text-destructive">Could not load script comparison</p>
                    <p class="mt-1 text-xs text-muted-foreground">{String(err)}</p>
                  </div>
                {/await}
              {/if}
            </div>
          </Tabs.Content>
        </Tabs.Root>
      </div>
    </div>
  </Dialog.Content>
</Dialog.Root>

// mobile-app/components/TypingHelper.tsx
import React, { useState, useEffect } from "react";
import {
  View,
  Text,
  Modal,
  TouchableOpacity,
  ScrollView,
  ActivityIndicator,
} from "react-native";
import { X, Keyboard, ArrowLeftRight } from "lucide-react-native";
import type { ScriptListType } from "lipilekhika";
import { SCRIPT_LIST } from "lipilekhika";
import { getScriptTypingDataMap, getScriptKramaData } from "lipilekhika/typing";
import { ScriptSelector } from "./ScriptSelector";
import type { TypingHelperProps } from "./types";
import { useTheme } from "./ThemeContext";

type ListType = "svara" | "vyanjana" | "anya" | "mAtrA";
type Item = [text: string, type: ListType, mappings: string[]];
type KramaRow = [text: string, type: ListType];

const isSvara = (t: ListType) => t === "svara" || t === "mAtrA";

const filterCategory = (
  items: Item[],
  category: "svara" | "vyanjana" | "anya",
): Item[] => {
  if (category === "svara") return items.filter(([, t]) => isSvara(t));
  if (category === "vyanjana") return items.filter(([, t]) => t === "vyanjana");
  return items.filter(([, t]) => t === "anya");
};

interface CharacterCardProps {
  char: string;
  mappings: string[];
  isDark: boolean;
}

function CharacterCard({ char, mappings, isDark }: CharacterCardProps) {
  return (
    <View
      className={`rounded-lg border p-2.5 ${
        isDark ? "border-zinc-700 bg-zinc-800" : "border-zinc-200 bg-white"
      }`}
    >
      <Text
        className={`text-xl font-semibold ${isDark ? "text-white" : "text-zinc-900"}`}
      >
        {char === "\u200d" ? "ZWJ" : char}
      </Text>
      <View className="mt-1.5 flex-row flex-wrap gap-1">
        {mappings.length === 0 ? (
          <Text
            className={`text-xs ${isDark ? "text-zinc-400" : "text-zinc-500"}`}
          >
            No mappings
          </Text>
        ) : (
          mappings.map((m, i) => (
            <View
              key={`${m}-${i}`}
              className={`rounded border px-1.5 py-0.5 ${
                isDark
                  ? "border-zinc-600 bg-zinc-700/50"
                  : "border-zinc-300 bg-zinc-100"
              }`}
            >
              <Text
                className={`font-mono text-[10px] ${
                  isDark ? "text-zinc-300" : "text-zinc-600"
                }`}
              >
                {m}
              </Text>
            </View>
          ))
        )}
      </View>
    </View>
  );
}

interface CompareCardProps {
  baseText: string;
  compareText: string;
  isDark: boolean;
}

function CompareCard({ baseText, compareText, isDark }: CompareCardProps) {
  return (
    <View
      className={`rounded-lg border p-2.5 ${
        isDark ? "border-zinc-700 bg-zinc-800" : "border-zinc-200 bg-white"
      }`}
    >
      <Text
        className={`text-xl font-semibold ${isDark ? "text-white" : "text-zinc-900"}`}
      >
        {baseText}
      </Text>
      <Text
        className={`mt-1 text-xl font-semibold ${isDark ? "text-zinc-400" : "text-zinc-500"}`}
      >
        {compareText || "—"}
      </Text>
    </View>
  );
}

export function TypingHelper({
  visible,
  onClose,
  script: initialScript,
}: TypingHelperProps) {
  const { isDark } = useTheme();
  const [script, setScript] = useState<ScriptListType>(initialScript);
  const [activeTab, setActiveTab] = useState<"typing-map" | "compare-scripts">(
    "typing-map",
  );
  const [scriptToCompare, setScriptToCompare] =
    useState<ScriptListType>("Romanized");
  const [showCompareSelector, setShowCompareSelector] = useState(false);

  // Typing map data
  const [typingMapData, setTypingMapData] = useState<{
    common: Item[];
    specific: Item[];
  } | null>(null);
  const [typingMapLoading, setTypingMapLoading] = useState(true);
  const [typingMapError, setTypingMapError] = useState<string | null>(null);

  // Compare data
  const [compareData, setCompareData] = useState<{
    base: KramaRow[];
    compare: KramaRow[];
  } | null>(null);
  const [compareLoading, setCompareLoading] = useState(false);
  const [compareError, setCompareError] = useState<string | null>(null);

  // Load typing map data
  useEffect(() => {
    if (!visible) return;

    setTypingMapLoading(true);
    setTypingMapError(null);
    getScriptTypingDataMap(script)
      .then((data) => {
        setTypingMapData({
          common: data.common_krama_map as Item[],
          specific: data.script_specific_krama_map as Item[],
        });
        setTypingMapLoading(false);
      })
      .catch((err) => {
        setTypingMapError(String(err));
        setTypingMapLoading(false);
      });
  }, [script, visible]);

  // Load compare data
  useEffect(() => {
    if (!visible || activeTab !== "compare-scripts" || !scriptToCompare) return;
    if (scriptToCompare === script) return;

    setCompareLoading(true);
    setCompareError(null);
    Promise.all([
      getScriptKramaData(script),
      getScriptKramaData(scriptToCompare),
    ])
      .then(([base, compare]) => {
        setCompareData({
          base: base as KramaRow[],
          compare: compare as KramaRow[],
        });
        setCompareLoading(false);
      })
      .catch((err) => {
        setCompareError(String(err));
        setCompareLoading(false);
      });
  }, [script, scriptToCompare, activeTab, visible]);

  useEffect(() => {
    setScript(initialScript);
  }, [initialScript]);

  const renderTypingMapTab = () => {
    if (typingMapLoading) {
      return (
        <View className="items-center justify-center py-12">
          <ActivityIndicator size="large" color="#3b82f6" />
          <Text
            className={`mt-3 ${isDark ? "text-zinc-400" : "text-zinc-500"}`}
          >
            Loading typing map...
          </Text>
        </View>
      );
    }

    if (typingMapError) {
      return (
        <View
          className={`rounded-lg border p-4 ${
            isDark
              ? "border-red-800/30 bg-red-900/10"
              : "border-red-200 bg-red-50"
          }`}
        >
          <Text className="font-medium text-red-500">
            Could not load typing map
          </Text>
          <Text
            className={`mt-1 text-xs ${isDark ? "text-zinc-400" : "text-zinc-500"}`}
          >
            {typingMapError}
          </Text>
        </View>
      );
    }

    if (!typingMapData) return null;

    const svaraItems = filterCategory(typingMapData.common, "svara");
    const vyanjanaItems = filterCategory(typingMapData.common, "vyanjana");
    const otherItems = filterCategory(typingMapData.common, "anya");
    const specificItems = typingMapData.specific;

    return (
      <View className="gap-6">
        {/* Svara */}
        <View>
          <Text
            className={`mb-2 text-lg font-semibold ${isDark ? "text-white" : "text-zinc-900"}`}
          >
            Svara
          </Text>
          <View className="flex-row flex-wrap gap-2">
            {svaraItems.map(([char, type, mappings], i) => (
              <View key={`${char}-${type}-${i}`} className="w-[48%]">
                <CharacterCard
                  char={char}
                  mappings={mappings}
                  isDark={isDark}
                />
              </View>
            ))}
          </View>
        </View>

        {/* Vyanjana */}
        <View>
          <Text
            className={`mb-2 text-lg font-semibold ${isDark ? "text-white" : "text-zinc-900"}`}
          >
            Vyanjana
          </Text>
          <View className="flex-row flex-wrap gap-2">
            {vyanjanaItems.map(([char, type, mappings], i) => (
              <View key={`${char}-${type}-${i}`} className="w-[48%]">
                <CharacterCard
                  char={char}
                  mappings={mappings}
                  isDark={isDark}
                />
              </View>
            ))}
          </View>
        </View>

        {/* Other */}
        <View>
          <Text
            className={`mb-2 text-lg font-semibold ${isDark ? "text-white" : "text-zinc-900"}`}
          >
            Other
          </Text>
          <View className="flex-row flex-wrap gap-2">
            {otherItems.map(([char, type, mappings], i) => (
              <View key={`${char}-${type}-${i}`} className="w-[48%]">
                <CharacterCard
                  char={char}
                  mappings={mappings}
                  isDark={isDark}
                />
              </View>
            ))}
          </View>
        </View>

        {/* Script-specific */}
        {specificItems.length > 0 && (
          <View>
            <Text
              className={`mb-2 text-lg font-semibold ${isDark ? "text-white" : "text-zinc-900"}`}
            >
              Script-specific Characters
            </Text>
            <View className="flex-row flex-wrap gap-2">
              {specificItems.map(([char, type, mappings], i) => (
                <View key={`${char}-${type}-${i}`} className="w-[48%]">
                  <CharacterCard
                    char={char}
                    mappings={mappings}
                    isDark={isDark}
                  />
                </View>
              ))}
            </View>
          </View>
        )}
      </View>
    );
  };

  const renderCompareTab = () => {
    const availableScripts = (SCRIPT_LIST as ScriptListType[]).filter(
      (s) => s !== script && s !== "Normal",
    );

    return (
      <View className="gap-4">
        <View className="flex-row items-center justify-between">
          <Text
            className={
              isDark ? "text-sm text-zinc-400" : "text-sm text-zinc-500"
            }
          >
            Current:{" "}
            <Text
              className={`font-medium ${isDark ? "text-white" : "text-zinc-900"}`}
            >
              {script}
            </Text>
          </Text>
          <View className="flex-row items-center gap-2">
            <Text
              className={
                isDark ? "text-sm text-zinc-400" : "text-sm text-zinc-500"
              }
            >
              Compare with
            </Text>
            <TouchableOpacity
              onPress={() => setShowCompareSelector(true)}
              className={`rounded-lg border px-3 py-1.5 ${
                isDark
                  ? "border-zinc-700 bg-zinc-800"
                  : "border-zinc-300 bg-white"
              }`}
            >
              <Text
                className={`text-sm ${isDark ? "text-white" : "text-zinc-900"}`}
              >
                {scriptToCompare}
              </Text>
            </TouchableOpacity>
          </View>
        </View>

        {compareLoading ? (
          <View className="items-center justify-center py-12">
            <ActivityIndicator size="large" color="#3b82f6" />
          </View>
        ) : compareError ? (
          <View
            className={`rounded-lg border p-4 ${
              isDark
                ? "border-red-800/30 bg-red-900/10"
                : "border-red-200 bg-red-50"
            }`}
          >
            <Text className="font-medium text-red-500">
              Could not load comparison
            </Text>
            <Text
              className={`mt-1 text-xs ${isDark ? "text-zinc-400" : "text-zinc-500"}`}
            >
              {compareError}
            </Text>
          </View>
        ) : compareData ? (
          <View className="flex-row flex-wrap gap-2">
            {compareData.base.map(([baseText], i) =>
              baseText.length > 0 ? (
                <View key={`${baseText}-${i}`} className="w-[48%]">
                  <CompareCard
                    baseText={baseText}
                    compareText={compareData.compare[i]?.[0] ?? ""}
                    isDark={isDark}
                  />
                </View>
              ) : null,
            )}
          </View>
        ) : null}

        {/* Compare script selector modal */}
        <Modal
          visible={showCompareSelector}
          transparent
          animationType="fade"
          onRequestClose={() => setShowCompareSelector(false)}
        >
          <TouchableOpacity
            className="flex-1 bg-black/60"
            activeOpacity={1}
            onPress={() => setShowCompareSelector(false)}
          >
            <View
              className={`mx-4 mt-32 max-h-[60%] rounded-xl p-4 ${
                isDark ? "bg-zinc-900" : "bg-white"
              }`}
            >
              <Text
                className={`mb-3 text-base font-medium ${
                  isDark ? "text-white" : "text-zinc-900"
                }`}
              >
                Select script to compare
              </Text>
              <ScrollView>
                {availableScripts.map((s) => (
                  <TouchableOpacity
                    key={s}
                    onPress={() => {
                      setScriptToCompare(s);
                      setShowCompareSelector(false);
                    }}
                    className={`rounded-lg px-3 py-2.5 ${
                      s === scriptToCompare
                        ? isDark
                          ? "bg-blue-600/20"
                          : "bg-blue-50"
                        : ""
                    }`}
                  >
                    <Text
                      className={`text-sm ${
                        s === scriptToCompare
                          ? "font-medium text-blue-500"
                          : isDark
                            ? "text-white"
                            : "text-zinc-900"
                      }`}
                    >
                      {s}
                    </Text>
                  </TouchableOpacity>
                ))}
              </ScrollView>
            </View>
          </TouchableOpacity>
        </Modal>
      </View>
    );
  };

  return (
    <Modal
      visible={visible}
      animationType="slide"
      presentationStyle="pageSheet"
      onRequestClose={onClose}
    >
      <View className={`flex-1 ${isDark ? "bg-zinc-900" : "bg-zinc-50"}`}>
        {/* Header */}
        <View
          className={`flex-row items-center justify-between border-b px-4 py-4 ${
            isDark ? "border-zinc-800" : "border-zinc-200"
          }`}
        >
          <View className="flex-row items-center gap-2">
            <Keyboard size={20} color="#3b82f6" />
            <Text
              className={`text-lg font-semibold ${isDark ? "text-white" : "text-zinc-900"}`}
            >
              Typing help
            </Text>
          </View>
          <TouchableOpacity onPress={onClose}>
            <X size={24} color={isDark ? "#9ca3af" : "#6b7280"} />
          </TouchableOpacity>
        </View>

        <ScrollView className="flex-1 px-4 py-4">
          {/* Script Selector */}
          <View className="mb-4 flex-row items-center justify-center gap-2">
            <Text
              className={
                isDark ? "text-sm text-zinc-400" : "text-sm text-zinc-500"
              }
            >
              Select Script
            </Text>
            <ScriptSelector script={script} onScriptChange={setScript} />
          </View>

          {/* Tabs */}
          <View
            className={`mb-4 flex-row rounded-lg p-1 ${
              isDark ? "bg-zinc-800" : "bg-zinc-200"
            }`}
          >
            <TouchableOpacity
              onPress={() => setActiveTab("typing-map")}
              className={`flex-1 flex-row items-center justify-center gap-2 rounded-md py-2.5 ${
                activeTab === "typing-map"
                  ? isDark
                    ? "bg-zinc-700"
                    : "bg-white shadow-sm"
                  : ""
              }`}
            >
              <Keyboard
                size={16}
                color={
                  activeTab === "typing-map"
                    ? isDark
                      ? "#fff"
                      : "#18181b"
                    : isDark
                      ? "#9ca3af"
                      : "#6b7280"
                }
              />
              <Text
                className={`text-sm font-medium ${
                  activeTab === "typing-map"
                    ? isDark
                      ? "text-white"
                      : "text-zinc-900"
                    : isDark
                      ? "text-zinc-400"
                      : "text-zinc-500"
                }`}
              >
                Typing Map
              </Text>
            </TouchableOpacity>
            <TouchableOpacity
              onPress={() => setActiveTab("compare-scripts")}
              className={`flex-1 flex-row items-center justify-center gap-2 rounded-md py-2.5 ${
                activeTab === "compare-scripts"
                  ? isDark
                    ? "bg-zinc-700"
                    : "bg-white shadow-sm"
                  : ""
              }`}
            >
              <ArrowLeftRight
                size={16}
                color={
                  activeTab === "compare-scripts"
                    ? isDark
                      ? "#fff"
                      : "#18181b"
                    : isDark
                      ? "#9ca3af"
                      : "#6b7280"
                }
              />
              <Text
                className={`text-sm font-medium ${
                  activeTab === "compare-scripts"
                    ? isDark
                      ? "text-white"
                      : "text-zinc-900"
                    : isDark
                      ? "text-zinc-400"
                      : "text-zinc-500"
                }`}
              >
                Compare Scripts
              </Text>
            </TouchableOpacity>
          </View>

          {/* Tab Content */}
          {activeTab === "typing-map"
            ? renderTypingMapTab()
            : renderCompareTab()}
        </ScrollView>
      </View>
    </Modal>
  );
}
